name: youhealthy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_core: 3.15.2
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  logger: ^1.4.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/treino.jpg
   - assets/images/saude.png
   - assets/images/exercicios.png
   - assets/images/frutas.png